# ****************************************************************************
# * Licensed Materials - Property of IBM
# * IBM Cloud Kubernetes Service, 5737-D43
# * (C) Copyright IBM Corp. 2021 All Rights Reserved.
# * US Government Users Restricted Rights - Use, duplication or
# * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# ****************************************************************************

# all available settings of specific linters
linters-settings:
  govet:
    # settings per analyzer
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  #gosec:
  #  settings:
  #    exclude: "G401"
  golint:
    min-confidence: 0
    report-comments: true
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
issues:
  include: [EXC01, EXC02]
  exclude-use-default: false
linters:
    # enable or disable analyzers by name
    enable:
      - golint
      - gofmt
      - whitespace
      - misspell
      - unconvert
      - goimports
      - unused
      - gosimple
      - varcheck
      - structcheck
      - bodyclose
      - deadcode
      - depguard
      - govet
      - typecheck
      - staticcheck
    enable-all: false
    disable-all: true

run:
  skip-dirs:
    - controllers/fake
    - tests
  skip-files:
    - utils/crn/crn_test.go
    - logger/logger_test.go
    - watcher/pv_watcher_test.go
    - utils/config/config_test.go
