FROM registry.access.redhat.com/ubi8/ubi-minimal8.7-1107
# Create Directory to hold all testing binaries
RUN mkdir /pvg-tests

# Add test binary to /pvg-tests directory
ADD pvg/armada-storage-e2e /pvg-tests/armada-storage-e2e
