FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6-751.1655117800
# Create Directory to hold all testing binaries
RUN mkdir /pvg-tests

# Add test binary to /pvg-tests directory
ADD pvg/armada-storage-e2e /pvg-tests/armada-storage-e2e
