apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  namespace: kube-system
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "ibm-cloud.kubernetes.io/iaas-provider"
                operator: In
                values:
                - softlayer
            - matchExpressions:
              - key: "ibm-cloud.kubernetes.io/iaas-provider"
                operator: DoesNotExist
      containers:
      - name: {{ .Chart.Name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.build }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /run/systemd
            name: sysd-run
          - mountPath: /host/etc
            name: host-etc
          - mountPath: /host/lib
            name: host-lib
          - mountPath: /host/var/log
            name: host-var-log
      serviceAccountName: ibmcloud-block-storage-attacher
      volumes:
        - name: sysd-run
          hostPath:
            path: /run/systemd
        - name: host-etc
          hostPath:
            path: /etc/
        - name: host-lib
          hostPath:
            path: /lib/
        - name: host-var-log
          hostPath:
            path: /var/log
