# ServiceAccount for ibmcloud-block-storage-attacher
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibmcloud-block-storage-attacher
  namespace: kube-system
imagePullSecrets:
  - name: bluemix-default-secret
  - name: bluemix-default-secret-regional
  - name: bluemix-default-secret-international
---
#ClusterRole with minimum permissions required for ibmcloud-block-storage-attacher
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ibmcloud-block-storage-attacher
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update"]
---
#ClusterRoleBinding for binding ClusterRole "ibmcloud-block-storage-plugin"
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ibmcloud-block-storage-attacher
subjects:
- kind: ServiceAccount
  name: ibmcloud-block-storage-attacher
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ibmcloud-block-storage-attacher
  apiGroup: rbac.authorization.k8s.io
