apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-block-attacher
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
provisioner: ibm.io/ibmc-blockattacher
parameters:
  attach: "true"
