#!/usr/bin/env python3.6

from px_iks_utils import IKS_vols
import sys

if len(sys.argv) < 2:
    print ("Usage: ", sys.argv[0], "  volId [...]")
    sys.exit(1)

s = len(sys.argv)
i = 1
while (i < s):
    print ("Deleting VolID: ", sys.argv[i])
    IKS_vols().delete_vol (sys.argv[i])
    i = i + 1

