#!/usr/bin/env python3.6

import os
import SoftLayer
from pprint import pprint as pp
from px_iks_utils import IKS_clusters, IKS_vols

IAMToken = os.popen("cat ~/.bluemix/config.json | jq .IAMToken").read().rstrip().strip('\"')
clusters = IKS_clusters(IAMToken=IAMToken).list()
hosts = {}
for c in clusters:
    for w in c['workers']:
        hosts[w['privateIP']] = { 'region': c['region'], 'cluster' : c['name'], 'worker' : w['id'] , 'location': w['location']}


volIDs = IKS_vols().listall()
print ("VolID             Size            HostIPaddr           Region          Cluster             Worker                                                       Location")
for vid in volIDs:
     vol = IKS_vols().get_vol (vid)
     if vol.acls:
         for a in vol.acls:  
             ip = a['hostIP']
             if ip in hosts:
                 print ("%s          %s            %s          %s         %s            %s              %s" %
                   (vid, vol.detail['capacityGb'], ip, hosts[ip]['region'], hosts[ip]['cluster'], hosts[ip]['worker'], hosts[ip]['location']))
             else:
                 print ("%s          %s            %s          %s            %s           %s" %
                   (vid, vol.detail['capacityGb'], ip, "", "", ""))
     else:
           print ("%s          %s            %s          %s            %s           %s" %
               (vid, vol.detail['capacityGb'], "", "", "", ""))

   
